---
driver:
  name: lxd_cli
  config:
    security.nesting: true

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: all
  ansible_verbose: true
  # ansible_verbose: false
  ansible_verbosity: 2
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  require_ansible_omnibus: true
  # planned for deprecation per https://docs.chef.io/workstation/config_yml_kitchen/
  require_chef_omnibus: false
  require_chef_for_busser: false
  # chef_omnibus_url: https://omnitruck.chef.io/install.sh
  enable_yum_epel: true
  ansible_connection: ssh
  ansible_omnibus_url: https://raw.githubusercontent.com/juju4/omnibus-ansible/master/ansible_install.sh

verifier:
  name: serverspec

platforms:
  - name: ubuntu-20.04
  - name: ubuntu-18.04
  # - name: centos-7

suites:
  - name: default
    run_list:
    attributes:
  - name: default-process
    run_list:
    attributes:
  - name: default-HEAD
    run_list:
    attributes:
  - name: default-docker
    run_list:
    attributes:
