---

- name: allow timesketch md5 auth
  ansible.builtin.lineinfile:
    dest: "{{ postgres_confdir }}/pg_hba.conf"
    line: 'local    all             timesketch                              md5'
    backup: true
  notify:
    - restart postgresql
