---

- block:
    - name: apt | remove conflicting packages with gift repository
      ansible.builtin.apt:
        name: "{{ timesketch_gift_remove }}"
        state: absent
      register: pkg_result
      until: pkg_result is success
  when: timesketch_gift_remove is defined and timesketch_gift_remove != []

- name: apt | timesketch packages dependencies
  ansible.builtin.apt:
    name: "{{ timesketch_pkg + timesketch_gift_pkg }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  register: pkg_result
  until: pkg_result is success

- name: Ubuntu | add universe repository
  ansible.builtin.apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
    state: present
  when: ansible_distribution == 'Ubuntu'
