---

- name: Add desktop shortcut
  ansible.builtin.template:
    src: timesketch.desktop.j2
    dest: "{{ item }}/timesketch.desktop"
    mode: '0600'
  with_items: "{{ timesketch_shortcut_list | default([]) }}"
