---

- name: git clone plaso
  ansible.builtin.git:
    repo: https://github.com/log2timeline/plaso.git
    dest: "{{ timesketch_pip_share }}/plaso"
    version: "{{ timesketch_plaso_version | default('20200121') }}"

- name: git clone l2tdevtools
  ansible.builtin.git:
    repo: https://github.com/log2timeline/l2tdevtools.git
    dest: "{{ timesketch_pip_share }}/l2tdevtools"
    version: "{{ timesketch_l2tdevtools_version | default('HEAD') }}"
    update: no
## rpm build might night to patch l2tdevtools/build_helper.py _BUILD_DEPENDENCIES
## centos7: s/python3-/python34-/g
## Fedora24: s/python-/python2-/g
- name: download and build with l2tdevtools  # noqa no-changed-when
  ansible.builtin.command: "{{ item }}"
  args:
    chdir: "{{ timesketch_pip_share }}/l2tdevtools"
  with_items:
    - "{{ timesketch_python_bin }} tools/build.py download"
    - "{{ timesketch_python_bin }} tools/build.py rpm"
  environment:
    PYTHONPATH: .
- name: install built rpm
  ansible.builtin.yum: name={{ item }} state=present
  with_fileglob:
    - "{{ timesketch_pip_share }}/l2tdevtools/build/*.rpm"
