---

- block:
    - name: url | retrieve images from url
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ timesketch_plaso_uploading_dir }}/{{ item.url | basename | regex_replace('\\?.*$', '') }}"
        mode: '0644'
        checksum: "{{ item.checksum }}"
      with_items: "{{ timesketch_process_url }}"

    - name: url | uncompress images from url
      ansible.builtin.unarchive:
        src: "{{ timesketch_plaso_uploading_dir }}/{{ item.url | basename | regex_replace('\\?.*$', '') }}"
        dest: "{{ timesketch_plaso_uploading_dir }}"
        copy: no
      with_items: "{{ timesketch_process_url }}"
  when: timesketch_process_url is defined and timesketch_process_url != []

- block:
    - name: file | retrieve images from orchestrator
      ansible.builtin.copy:
        src: "{{ item.url }}"
        dest: "{{ timesketch_plaso_uploading_dir }}/{{ item.url | basename | regex_replace('\\?.*$', '') }}"
        mode: '0644'
      with_items: "{{ timesketch_process_files }}"
  when: timesketch_process_files is defined and timesketch_process_files != []

- name: Debug | timesketch_process_url
  ansible.builtin.debug: var=timesketch_process_url
- name: Debug | timesketch_process_files
  ansible.builtin.debug: var=timesketch_process_files
- name: Notify command
  ansible.builtin.debug:
    msg: >
      launching cmd{{ ':' }} log2timeline.py --logfile {{ timesketch_plaso_uploading_dir }}/{{ item.plasofile }}.log
        {{ timesketch_plaso_uploading_dir }}/{{ item.plasofile }}.plaso
        {{ timesketch_plaso_uploading_dir }}/{{ item.plasofile }}
  with_items: "{{ timesketch_process_url }}"
- name: process image with log2timeline
  ## debug: --disable_zeromq --profile --profiling_type memory
  ansible.builtin.command: >
    log2timeline.py --logfile {{ timesketch_plaso_uploading_dir }}/{{ item.plasofile }}.log
        {{ timesketch_plaso_uploading_dir }}/{{ item.plasofile }}.plaso
        {{ timesketch_plaso_uploading_dir }}/{{ item.plasofile }}
  args:
    creates: "{{ timesketch_plaso_uploading_dir }}/{{ item.plasofile }}.plaso"
  with_items: "{{ timesketch_process_url }}"
  # with_items: "{{ timesketch_process_url + timesketch_process_files }}"

- name: check version of psort
  ansible.builtin.command: psort.py -V
  register: psortversion
  changed_when: false
- name: Debug | psortversion
  ansible.builtin.debug: var=psortversion
- name: Command
  ansible.builtin.debug:
    msg: >
      launching cmd{{ ':' }} psort.py -d --logfile {{ timesketch_plaso_uploading_dir }}/{{ item.plasofile }}-psort.log
        -o timesketch {{ timesketch_plaso_uploading_dir }}/{{ item.plasofile }}.plaso
  with_items: "{{ timesketch_process_url }}"

- name: process image with psort
  ansible.builtin.command: >
    psort.py -d --logfile {{ timesketch_plaso_uploading_dir }}/{{ item.plasofile }}-psort.log
        -o timesketch {{ timesketch_plaso_uploading_dir }}/{{ item.plasofile }}.plaso
  args:
    creates: "{{ timesketch_plaso_uploading_dir }}/{{ item.plasofile }}-psort.log"
  with_items: "{{ timesketch_process_url }}"
  # with_items: "{{ timesketch_process_url + timesketch_process_files }}"
  failed_when: false
  async: 1800
  # async: 3600
  poll: 60

- name: retrieve plaso files on orchestrator
  ansible.builtin.fetch:
    src: "{{ timesketch_plaso_uploading_dir }}/{{ item.url | basename }}.plaso"
    dest: "{{ timesketch_retrieve_dir }}"
    mode: '0400'
  with_items: "{{ timesketch_process_url }}"
  # with_items: "{{ timesketch_process_url + timesketch_process_files }}"
  when: timesketch_retrieve_plasofile is defined and timesketch_retrieve_plasofile
