---

- name: Ubuntu | add universe repository
  ansible.builtin.apt_repository: repo="deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe" state=present
- name: Ubuntu | add gift/stable ppa
  ansible.builtin.apt_repository: repo='ppa:gift/stable' state=present
  when: ansible_distribution_release == 'trusty'

- name: Ubuntu | Install Plaso
  ansible.builtin.apt: name=python-plaso state=present update_cache=yes
