---

- name: restart supervisor
  ansible.builtin.service: name={{ supervisor_service }} state=restarted sleep=5

- name: restart postgresql
  ansible.builtin.service: name=postgresql state=restarted

- name: restart timesketch docker-compose
  docker_compose:
    project_src: "{{ timesketch_root }}"
    build: no
    state: present
  environment:
    DOCKER_CLIENT_TIMEOUT: 120
    COMPOSE_HTTP_TIMEOUT: 120

- name: pause
  ansible.builtin.pause: seconds=5
